reporting:
  description: >
    Review the {retrieved_data} and user queries and expand this information into a
    a report. Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'. Must answer the user query/question.
  agent: reporter