services:
  postgres:
    image: postgres:latest
    container_name: n8n-postgres
    restart: always
    environment:
        - POSTGRES_DB=n8n-db
        - POSTGRES_USER=n8n-user
        - POSTGRES_PASSWORD=123456
    ports:
        - 5432:5432
    expose:
        - 5432
    volumes:
        - ./volume/postgresql/:/var/lib/postgresql/data

networks:
  host:
