query_exectution:
  description: >
    Analyse user query or queries and translate them into accurate and efficient
    SQL queries and then execute them using retrieval tool.
  expected_output: >
    some rows from one or several databases
  agent: sql_query_translator

reporting:
  description: >
    Review the retrieved data and user queries and expand this information into a
    a report. Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'. Must answer the user query/question.
  agent: reporter
  context:
    - query_exectution